// eslint.config.js
import pluginConfigVue from 'eslint-plugin-vue';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import tsEslint from 'typescript-eslint';
import vueParser from 'vue-eslint-parser';

export default defineConfig([
    ...pluginConfigVue.configs['flat/essential'],
    ...tsEslint.configs.recommended,
    {
        files: ['**/*.{js,mjs,cjs,ts,mts,cts,vue}'],
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.node,
            },
            ecmaVersion: 'latest',
            sourceType: 'module',
            parser: vueParser,
            parserOptions: {
                parser: tsEslint.parser,
                extraFileExtensions: ['.vue'],
                ecmaVersion: 'latest',
                sourceType: 'module',
            },
        },
        rules: {
            'no-console': 'error',
            'array-bracket-spacing': ['warn', 'never'],
            'no-trailing-spaces': 'warn',
            'no-undef': 'warn',
            quotes: ['warn', 'single'],
            'space-in-parens': ['warn', 'never'],
            'space-infix-ops': 'warn',
            strict: ['warn', 'never'],
            semi: ['error', 'always'],
            'valid-typeof': 'warn',
            'vue/attribute-hyphenation': 'warn',
            'vue/html-end-tags': 'warn',
            'vue/html-indent': ['warn', 2],
            'vue/html-quotes': 'warn',
            'vue/html-self-closing': 'off',
            'vue/html-closing-bracket-newline': ['error', { singleline: 'never', multiline: 'always' }],
            'vue/mustache-interpolation-spacing': 'warn',
            'vue/component-definition-name-casing': 'warn',
            'vue/no-async-in-computed-properties': 'warn',
            'vue/no-use-v-if-with-v-for': 'warn',
            'vue/no-dupe-keys': 'warn',
            'vue/no-duplicate-attributes': 'warn',
            'vue/no-multi-spaces': 'warn',
            'vue/no-reserved-keys': 'warn',
            'vue/no-shared-component-data': 'warn',
            'vue/no-side-effects-in-computed-properties': 'warn',
            'vue/no-template-key': 'warn',
            'vue/no-unused-vars': 'warn',
            'vue/order-in-components': 'warn',
            'vue/require-default-prop': 'warn',
            'vue/require-prop-types': 'warn',
            'vue/require-render-return': 'warn',
            'vue/require-valid-default-prop': 'warn',
            'vue/return-in-computed-property': 'warn',
            'vue/script-indent': [
                'error',
                2,
                {
                    baseIndent: 1,
                    switchCase: 1,
                    ignores: [],
                },
            ],
            'vue/this-in-template': 'warn',
            'vue/v-bind-style': 'warn',
            'vue/v-on-style': 'warn',
            'vue/multi-word-component-names': 'off',
            'no-unused-vars': 'off',
            'brace-style': 'warn',
            'comma-dangle': ['warn', 'always-multiline'],
            'comma-spacing': ['warn', { before: false, after: true }],
            'constructor-super': 'warn',
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/no-floating-promises': 'off',
            '@typescript-eslint/no-unused-vars': 'error',
            '@typescript-eslint/naming-convention': [
                'warn',
                {
                    selector: 'objectLiteralProperty',
                    format: ['camelCase', 'UPPER_CASE', 'snake_case'],
                    filter: {
                        regex: '^(vue/|@|.*-.*)',
                        match: false,
                    },
                },
            ],
        },
    },
    {
        ignores: [
            'node_modules/**',
            'dist/**',
            'build/**',
            'public/**',
            'vendor/**',
            'bootstrap/cache/**',
            'storage/**',
            'e',
            '*.php',
            '*.json',
            '.eslintrc.ts',
            '*config.ts',
        ],
    },
]);
