import { type Config } from 'prettier';

const config: Config = {
	endOfLine: 'lf',
	printWidth: 120,
	singleQuote: true,
	vueIndentScriptAndStyle: true,
	importOrderParserPlugins: ['typescript', 'vue'],
	plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
	importOrder: [
		'<BUILTIN_MODULES>',
		'^vue$',
		'<THIRD_PARTY_MODULES>',
		'^@/Apollo',
		'^@/Router',
		'^@/Store',
		'^config',
		'^@/Types',
		'^@/Composables',
		'^@/Components',
		'^@/Pages/(.*)$',
		'^\\.\\./(.*)$',
		'^[./]',
		'^@/images',
		'^.+\\.svg$',
		'^.+\\.scss$',
	],
	importOrderSeparation: true,
	importOrderSortSpecifiers: true,
	tailwindConfig: './tailwind.config.ts', // remove if using Tailwind v4
	tailwindAttributes: [
		'class',
		'className',
		'container-classes',
		'first-bg-classes',
		'second-bg-classes',
		'text-left-classes',
		'text-right-classes',
		'containerClasses',
		'firstBgClasses',
		'secondBgClasses',
		'textLeftClasses',
		'textRightClasses',
		':container-classes',
		':first-bg-classes',
		':second-bg-classes',
		':text-left-classes',
		':text-right-classes',
		':containerClasses',
		':firstBgClasses',
		':secondBgClasses',
		':textLeftClasses',
		':textRightClasses',
	],
	// tailwindFunctions is valid but missing from Prettier's Config type
	// @ts-ignore
	tailwindFunctions: ['tw', 'twMerge'],
};

export default config;
