import { type Config } from 'prettier';

const config: Config = {
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: 'lf',
  printWidth: 120,
  semi: true,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'all',
  useTabs: false,
  vueIndentScriptAndStyle: true,
  importOrder: [
    '^vue$',
    '^@/Types',
    '^@/Store',
    '^@/Components',
    '^@/Composables',
    '^@/images',
    '^[./]',
    '^mock/',
    '^config',
    '^utils/',
    '^hooks/',
    '^.+\\.svg$',
    '^.+\\.scss$',
    '^interface',
    '^(?=content|api)',
    '^(components/|./index)',
    '^\\.\\./(.*)$',
    '^(?=./styles.module.scss)',
    '^(?=./types)',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderParserPlugins: ['typescript', 'vue'],
  plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  tailwindConfig: './tailwind.config.ts',
  tailwindAttributes: [
    'class',
    'className',
    'container-classes',
    'first-bg-classes',
    'second-bg-classes',
    'text-left-classes',
    'text-right-classes',
    'containerClasses',
    'firstBgClasses',
    'secondBgClasses',
    'textLeftClasses',
    'textRightClasses',
    ':container-classes',
    ':first-bg-classes',
    ':second-bg-classes',
    ':text-left-classes',
    ':text-right-classes',
    ':containerClasses',
    ':firstBgClasses',
    ':secondBgClasses',
    ':textLeftClasses',
    ':textRightClasses',
  ],
  // @ts-ignore
  tailwindFunctions: ['tw', 'twMerge'],
};

export default config;
